//! # Pallet ATS
//!
//! Substrate pallet for the Allfeat Timestamp Service (ATS).
//!
//! Stores tamper-proof, timestamped commitments for musical works on-chain.
//! Only the 32-byte SHA-256 commitment hash goes on-chain; all data stays off-chain
//! and is generated by the `ats-sdk` crate.
//!
//! ## Features
//!
//! - **Auto-incremented IDs** (`u64`) for each ATS entry
//! - **Versioning**: each ATS can have multiple versions, each with its own commitment
//! - **Deposits**: configurable base and version deposits using fungible holds
//! - **Hard delete on revocation**: full cleanup with deposit restitution
//! - **On-behalf (delegate) operations**: an operator can create/update/revoke ATS entries
//!   on behalf of an owner, paying deposits and fees, authorized via off-chain signatures

#![cfg_attr(not(feature = "std"), no_std)]

extern crate alloc;

mod types;
pub use types::*;

/// Storage migrations.
pub mod migrations;

/// Weight information for pallet extrinsics.
pub mod weights;
pub use weights::WeightInfo;

#[cfg(feature = "runtime-benchmarks")]
mod benchmarking;

#[cfg(test)]
mod mock;

#[cfg(test)]
mod tests;

pub use pallet_ats_primitives::*;

/// Helper trait for generating valid signatures during benchmarks.
///
/// Follows the same pattern as `pallet-verify-signature`: the helper receives
/// arbitrary `entropy` bytes (to seed key generation) and the `msg` to sign,
/// and returns a `(Signature, AccountId)` pair that will pass verification.
///
/// A blanket `()` implementation is provided for runtimes using
/// `MultiSignature` / `AccountId32`, which delegates to `sp_io` host
/// functions and works without `sp-core/full_crypto`.
#[cfg(feature = "runtime-benchmarks")]
pub trait BenchmarkHelper<Signature, AccountId> {
    /// Create a valid `(signature, signer_account)` pair for `msg`.
    ///
    /// `entropy` can be used to derive different key pairs across calls.
    fn create_signature(entropy: &[u8], msg: &[u8]) -> (Signature, AccountId);
}

/// Default implementation for runtimes using `MultiSignature` / `AccountId32`.
///
/// Uses `sp_io` host functions (keystore) to generate keys and sign,
/// so it works in `no_std` benchmark environments without `sp-core/full_crypto`.
#[cfg(feature = "runtime-benchmarks")]
impl BenchmarkHelper<sp_runtime::MultiSignature, sp_runtime::AccountId32> for () {
    fn create_signature(
        entropy: &[u8],
        msg: &[u8],
    ) -> (sp_runtime::MultiSignature, sp_runtime::AccountId32) {
        use sp_runtime::traits::IdentifyAccount as _;
        // Build a valid SecretUri derivation path from the entropy bytes.
        let uri = alloc::format!("//{}", core::str::from_utf8(entropy).unwrap_or("bench"));
        let public = sp_io::crypto::sr25519_generate(0.into(), Some(uri.into_bytes()));
        let account: sp_runtime::AccountId32 =
            sp_runtime::MultiSigner::Sr25519(public).into_account();
        let signature = sp_runtime::MultiSignature::Sr25519(
            sp_io::crypto::sr25519_sign(0.into(), &public, msg)
                .expect("keystore available in benchmark context; qed"),
        );
        (signature, account)
    }
}

pub use pallet::*;

#[frame_support::pallet]
pub mod pallet {
    use super::*;
    use codec::Encode;
    use frame_support::{
        pallet_prelude::*,
        traits::fungible::{self, hold::Mutate as FunHoldMutate},
        traits::tokens::Precision,
    };
    use frame_system::pallet_prelude::*;
    use sp_runtime::traits::CheckedAdd;
    use sp_runtime::traits::{IdentifyAccount, Verify};

    /// Current storage version.
    const STORAGE_VERSION: StorageVersion = StorageVersion::new(2);

    /// Balance type derived from the pallet's currency configuration.
    pub type BalanceOf<T> = <<T as Config>::Currency as fungible::Inspect<
        <T as frame_system::Config>::AccountId,
    >>::Balance;

    /// Concrete ATS record type for this pallet's configuration.
    pub type AtsRecordOf<T> =
        AtsRecord<<T as frame_system::Config>::AccountId, BlockNumberFor<T>, BalanceOf<T>>;

    /// Concrete version info type for this pallet's configuration.
    pub type VersionInfoOf<T> = VersionInfo<BlockNumberFor<T>>;

    #[pallet::pallet]
    #[pallet::storage_version(STORAGE_VERSION)]
    pub struct Pallet<T>(_);

    /// Configuration trait for the ATS pallet.
    #[pallet::config]
    pub trait Config: frame_system::Config {
        /// The overarching hold reason type.
        type RuntimeHoldReason: From<HoldReason>;

        /// The currency type supporting fungible holds.
        type Currency: fungible::Inspect<Self::AccountId>
            + fungible::Mutate<Self::AccountId>
            + fungible::hold::Inspect<Self::AccountId, Reason = Self::RuntimeHoldReason>
            + fungible::hold::Mutate<Self::AccountId, Reason = Self::RuntimeHoldReason>;

        /// Off-chain signature type used for on-behalf authorization.
        type OffchainSignature: Verify<Signer = Self::Signer>
            + codec::Codec
            + Clone
            + PartialEq
            + Eq
            + TypeInfo
            + core::fmt::Debug;

        /// Signer type that maps to account IDs.
        type Signer: IdentifyAccount<AccountId = Self::AccountId>
            + codec::Codec
            + Clone
            + PartialEq
            + Eq
            + TypeInfo
            + core::fmt::Debug;

        /// Base deposit required to create a new ATS entry.
        #[pallet::constant]
        type BaseDeposit: Get<BalanceOf<Self>>;

        /// Deposit required per version of an ATS entry.
        #[pallet::constant]
        type VersionDeposit: Get<BalanceOf<Self>>;

        /// Maximum number of versions allowed per ATS entry.
        #[pallet::constant]
        type MaxVersionsPerAts: Get<u32>;

        /// Maximum number of ATS entries allowed per account.
        #[pallet::constant]
        type MaxAtsPerAccount: Get<u32>;

        /// Weight information for pallet extrinsics.
        type WeightInfo: crate::WeightInfo;

        /// Helper for generating valid signatures in benchmarks.
        ///
        /// Production runtimes using `MultiSignature` / `AccountId32` can use `()`.
        #[cfg(feature = "runtime-benchmarks")]
        type BenchmarkHelper: crate::BenchmarkHelper<Self::OffchainSignature, Self::AccountId>;
    }

    /// Reasons for holding funds.
    #[pallet::composite_enum]
    pub enum HoldReason {
        /// Deposit for an ATS entry (base + all version deposits aggregated).
        #[codec(index = 0)]
        AtsDeposit,
    }

    /// Auto-incrementing counter for the next ATS identifier.
    #[pallet::storage]
    pub type NextAtsId<T: Config> = StorageValue<_, u64, ValueQuery>;

    /// Registry mapping ATS IDs to their records.
    #[pallet::storage]
    pub type AtsRegistry<T: Config> =
        StorageMap<_, Blake2_128Concat, AtsId, AtsRecordOf<T>, OptionQuery>;

    /// Double map storing version info for each ATS entry.
    #[pallet::storage]
    pub type AtsVersions<T: Config> = StorageDoubleMap<
        _,
        Blake2_128Concat,
        AtsId,
        Blake2_128Concat,
        u32,
        VersionInfoOf<T>,
        OptionQuery,
    >;

    /// Index mapping account IDs to their owned ATS entries.
    #[pallet::storage]
    pub type OwnerIndex<T: Config> = StorageMap<
        _,
        Blake2_128Concat,
        T::AccountId,
        BoundedVec<AtsId, T::MaxAtsPerAccount>,
        ValueQuery,
    >;

    /// Per-owner nonce for on-behalf signature replay protection.
    #[pallet::storage]
    pub type OnBehalfNonce<T: Config> =
        StorageMap<_, Blake2_128Concat, T::AccountId, u64, ValueQuery>;

    /// Events emitted by the ATS pallet.
    #[pallet::event]
    #[pallet::generate_deposit(pub(super) fn deposit_event)]
    pub enum Event<T: Config> {
        /// A new ATS entry was created.
        AtsCreated {
            /// The assigned ATS identifier.
            ats_id: AtsId,
            /// The account that owns the entry.
            owner: T::AccountId,
            /// The SHA-256 commitment hash.
            commitment: [u8; 32],
            /// The protocol version.
            protocol_version: u8,
            /// The operator that acted on behalf, if any.
            operator: Option<T::AccountId>,
        },
        /// An ATS entry was updated with a new version.
        AtsUpdated {
            /// The ATS identifier.
            ats_id: AtsId,
            /// The new version number.
            version: u32,
            /// The SHA-256 commitment hash for this version.
            commitment: [u8; 32],
            /// The protocol version.
            protocol_version: u8,
            /// The operator that acted on behalf, if any.
            operator: Option<T::AccountId>,
        },
        /// An ATS entry was revoked and all deposits returned.
        AtsRevoked {
            /// The revoked ATS identifier.
            ats_id: AtsId,
            /// The owner who revoked the entry.
            owner: T::AccountId,
            /// The operator that acted on behalf, if any.
            operator: Option<T::AccountId>,
        },
    }

    /// Errors returned by the ATS pallet.
    #[pallet::error]
    pub enum Error<T> {
        /// The specified ATS entry was not found.
        AtsNotFound,
        /// The caller is not the owner of the ATS entry.
        NotOwner,
        /// Maximum number of versions reached for this ATS entry.
        MaxVersionsReached,
        /// Invalid protocol version (must be non-zero).
        InvalidProtocolVersion,
        /// Maximum number of ATS entries per account reached.
        MaxAtsPerAccountReached,
        /// Arithmetic overflow occurred.
        ArithmeticOverflow,
        /// The provided off-chain signature is invalid.
        InvalidSignature,
        /// The provided nonce does not match the expected value.
        InvalidNonce,
        /// Maximum number of unique depositors reached for this ATS entry.
        MaxDepositorsReached,
    }

    #[pallet::call]
    impl<T: Config> Pallet<T> {
        /// Create a new ATS entry with an initial version (version 0).
        ///
        /// Holds `BaseDeposit + VersionDeposit` from the caller's balance in a single hold.
        #[pallet::call_index(0)]
        #[pallet::weight(T::WeightInfo::create(T::MaxAtsPerAccount::get()))]
        pub fn create(
            origin: OriginFor<T>,
            commitment: [u8; 32],
            protocol_version: u8,
        ) -> DispatchResult {
            let who = ensure_signed(origin)?;
            Self::do_create(who.clone(), who, commitment, protocol_version, None)
        }

        /// Add a new version to an existing ATS entry.
        ///
        /// Holds `VersionDeposit` from the caller's balance. Only the owner can update.
        #[pallet::call_index(1)]
        #[pallet::weight(T::WeightInfo::update(T::MaxVersionsPerAts::get()))]
        pub fn update(
            origin: OriginFor<T>,
            ats_id: AtsId,
            commitment: [u8; 32],
            protocol_version: u8,
        ) -> DispatchResult {
            let who = ensure_signed(origin)?;
            Self::do_update(who.clone(), who, ats_id, commitment, protocol_version, None)
        }

        /// Revoke an ATS entry, deleting all versions and returning all deposits.
        ///
        /// This is a hard delete: all data is removed from storage. Only the owner can revoke.
        /// Deposits are returned to the original depositors (which may differ for on-behalf
        /// operations).
        /// Weight is linear in the number of versions.
        #[pallet::call_index(2)]
        #[pallet::weight(T::WeightInfo::revoke(T::MaxVersionsPerAts::get()))]
        pub fn revoke(origin: OriginFor<T>, ats_id: AtsId) -> DispatchResult {
            let who = ensure_signed(origin)?;
            Self::do_revoke(who, ats_id, None)
        }

        /// Create a new ATS entry on behalf of an owner.
        ///
        /// The caller (operator) pays all deposits and fees. The `owner` signs a payload
        /// authorizing this specific operation with a nonce for replay protection.
        #[pallet::call_index(3)]
        #[pallet::weight(T::WeightInfo::create_on_behalf(T::MaxAtsPerAccount::get()))]
        pub fn create_on_behalf(
            origin: OriginFor<T>,
            owner: T::AccountId,
            commitment: [u8; 32],
            protocol_version: u8,
            nonce: u64,
            signature: T::OffchainSignature,
        ) -> DispatchResult {
            let operator = ensure_signed(origin)?;

            // Verify nonce
            let current_nonce = OnBehalfNonce::<T>::get(&owner);
            ensure!(nonce == current_nonce, Error::<T>::InvalidNonce);

            // Verify signature
            let payload = CreateOnBehalfPayload {
                action: OnBehalfAction::Create,
                commitment,
                protocol_version,
                operator: operator.clone(),
                nonce,
            };
            Self::verify_signature(&payload.encode(), &signature, &owner)?;

            // Increment nonce
            OnBehalfNonce::<T>::insert(&owner, current_nonce.saturating_add(1));

            Self::do_create(
                owner,
                operator.clone(),
                commitment,
                protocol_version,
                Some(operator),
            )
        }

        /// Update an ATS entry on behalf of the owner.
        ///
        /// The caller (operator) pays the version deposit. The `owner` signs a payload
        /// authorizing this specific update with a nonce for replay protection.
        #[pallet::call_index(4)]
        #[pallet::weight(T::WeightInfo::update_on_behalf(T::MaxVersionsPerAts::get()))]
        pub fn update_on_behalf(
            origin: OriginFor<T>,
            owner: T::AccountId,
            ats_id: AtsId,
            commitment: [u8; 32],
            protocol_version: u8,
            nonce: u64,
            signature: T::OffchainSignature,
        ) -> DispatchResult {
            let operator = ensure_signed(origin)?;

            // Verify nonce
            let current_nonce = OnBehalfNonce::<T>::get(&owner);
            ensure!(nonce == current_nonce, Error::<T>::InvalidNonce);

            // Verify signature
            let payload = UpdateOnBehalfPayload {
                action: OnBehalfAction::Update,
                ats_id,
                commitment,
                protocol_version,
                operator: operator.clone(),
                nonce,
            };
            Self::verify_signature(&payload.encode(), &signature, &owner)?;

            // Increment nonce
            OnBehalfNonce::<T>::insert(&owner, current_nonce.saturating_add(1));

            Self::do_update(
                owner,
                operator.clone(),
                ats_id,
                commitment,
                protocol_version,
                Some(operator),
            )
        }

        /// Revoke an ATS entry on behalf of the owner.
        ///
        /// Deposits are returned to the original depositors. The `owner` signs a payload
        /// authorizing this specific revocation with a nonce for replay protection.
        #[pallet::call_index(5)]
        #[pallet::weight(T::WeightInfo::revoke_on_behalf(T::MaxVersionsPerAts::get()))]
        pub fn revoke_on_behalf(
            origin: OriginFor<T>,
            owner: T::AccountId,
            ats_id: AtsId,
            nonce: u64,
            signature: T::OffchainSignature,
        ) -> DispatchResult {
            let operator = ensure_signed(origin)?;

            // Verify nonce
            let current_nonce = OnBehalfNonce::<T>::get(&owner);
            ensure!(nonce == current_nonce, Error::<T>::InvalidNonce);

            // Verify signature
            let payload = RevokeOnBehalfPayload {
                action: OnBehalfAction::Revoke,
                ats_id,
                operator: operator.clone(),
                nonce,
            };
            Self::verify_signature(&payload.encode(), &signature, &owner)?;

            // Increment nonce
            OnBehalfNonce::<T>::insert(&owner, current_nonce.saturating_add(1));

            Self::do_revoke(owner, ats_id, Some(operator))
        }
    }

    // ── Internal helpers ───────────────────────────────────────────────────

    impl<T: Config> Pallet<T> {
        /// Core logic for creating an ATS entry.
        fn do_create(
            owner: T::AccountId,
            depositor: T::AccountId,
            commitment: [u8; 32],
            protocol_version: u8,
            operator: Option<T::AccountId>,
        ) -> DispatchResult {
            ensure!(protocol_version > 0, Error::<T>::InvalidProtocolVersion);

            // Check owner capacity
            let mut ids = OwnerIndex::<T>::get(&owner);
            ids.try_push(0) // dummy value to test capacity
                .map_err(|_| Error::<T>::MaxAtsPerAccountReached)?;
            ids.pop(); // remove the dummy

            // Allocate next ID
            let ats_id = NextAtsId::<T>::get();
            let next_id = ats_id
                .checked_add(1)
                .ok_or(Error::<T>::ArithmeticOverflow)?;

            // Hold combined deposit (base + version) in a single hold
            let base_deposit = T::BaseDeposit::get();
            let version_deposit = T::VersionDeposit::get();
            let total_deposit = base_deposit
                .checked_add(&version_deposit)
                .ok_or(Error::<T>::ArithmeticOverflow)?;
            <T::Currency as FunHoldMutate<T::AccountId>>::hold(
                &HoldReason::AtsDeposit.into(),
                &depositor,
                total_deposit,
            )?;

            let now = frame_system::Pallet::<T>::block_number();

            // Build deposits vec with single entry
            let mut deposits = BoundedVec::new();
            deposits
                .try_push(DepositEntry {
                    depositor: depositor.clone(),
                    amount: total_deposit,
                })
                .expect("first entry always fits; qed");

            // Write storage
            AtsRegistry::<T>::insert(
                ats_id,
                AtsRecordOf::<T> {
                    owner: owner.clone(),
                    created_at: now,
                    version_count: 1,
                    deposits,
                },
            );

            AtsVersions::<T>::insert(
                ats_id,
                0u32,
                VersionInfoOf::<T> {
                    commitment,
                    protocol_version,
                    created_at: now,
                },
            );

            // Update owner index (capacity already verified)
            ids.try_push(ats_id).expect("capacity checked above; qed");
            OwnerIndex::<T>::insert(&owner, ids);
            NextAtsId::<T>::put(next_id);

            Self::deposit_event(Event::AtsCreated {
                ats_id,
                owner,
                commitment,
                protocol_version,
                operator,
            });

            Ok(())
        }

        /// Core logic for updating an ATS entry with a new version.
        fn do_update(
            owner: T::AccountId,
            depositor: T::AccountId,
            ats_id: AtsId,
            commitment: [u8; 32],
            protocol_version: u8,
            operator: Option<T::AccountId>,
        ) -> DispatchResult {
            ensure!(protocol_version > 0, Error::<T>::InvalidProtocolVersion);

            let mut record = AtsRegistry::<T>::get(ats_id).ok_or(Error::<T>::AtsNotFound)?;
            ensure!(record.owner == owner, Error::<T>::NotOwner);

            let version = record.version_count;
            ensure!(
                version < T::MaxVersionsPerAts::get(),
                Error::<T>::MaxVersionsReached
            );
            let new_count = version
                .checked_add(1)
                .ok_or(Error::<T>::ArithmeticOverflow)?;

            // Hold version deposit from depositor
            let version_deposit = T::VersionDeposit::get();
            <T::Currency as FunHoldMutate<T::AccountId>>::hold(
                &HoldReason::AtsDeposit.into(),
                &depositor,
                version_deposit,
            )?;

            let now = frame_system::Pallet::<T>::block_number();

            AtsVersions::<T>::insert(
                ats_id,
                version,
                VersionInfoOf::<T> {
                    commitment,
                    protocol_version,
                    created_at: now,
                },
            );

            // Update or insert deposit entry for this depositor
            if let Some(entry) = record
                .deposits
                .iter_mut()
                .find(|e| e.depositor == depositor)
            {
                entry.amount = entry
                    .amount
                    .checked_add(&version_deposit)
                    .ok_or(Error::<T>::ArithmeticOverflow)?;
            } else {
                record
                    .deposits
                    .try_push(DepositEntry {
                        depositor,
                        amount: version_deposit,
                    })
                    .map_err(|_| Error::<T>::MaxDepositorsReached)?;
            }

            record.version_count = new_count;
            AtsRegistry::<T>::insert(ats_id, record);

            Self::deposit_event(Event::AtsUpdated {
                ats_id,
                version,
                commitment,
                protocol_version,
                operator,
            });

            Ok(())
        }

        /// Core logic for revoking an ATS entry.
        ///
        /// Deposits are released per unique depositor (O(d) releases instead of O(v)),
        /// and versions are batch-deleted via `clear_prefix`.
        fn do_revoke(
            owner: T::AccountId,
            ats_id: AtsId,
            operator: Option<T::AccountId>,
        ) -> DispatchResult {
            let record = AtsRegistry::<T>::take(ats_id).ok_or(Error::<T>::AtsNotFound)?;
            ensure!(record.owner == owner, Error::<T>::NotOwner);

            // Release aggregated deposits to each depositor
            for entry in &record.deposits {
                <T::Currency as FunHoldMutate<T::AccountId>>::release(
                    &HoldReason::AtsDeposit.into(),
                    &entry.depositor,
                    entry.amount,
                    Precision::Exact,
                )?;
            }

            // Batch-delete all version records
            let _ = AtsVersions::<T>::clear_prefix(ats_id, record.version_count, None);

            // Remove from owner index
            let mut ids = OwnerIndex::<T>::get(&owner);
            ids.retain(|id| *id != ats_id);
            if ids.is_empty() {
                OwnerIndex::<T>::remove(&owner);
            } else {
                OwnerIndex::<T>::insert(&owner, ids);
            }

            Self::deposit_event(Event::AtsRevoked {
                ats_id,
                owner,
                operator,
            });

            Ok(())
        }

        /// Verify an off-chain signature against an expected signer account.
        fn verify_signature(
            payload_bytes: &[u8],
            signature: &T::OffchainSignature,
            expected_signer: &T::AccountId,
        ) -> DispatchResult {
            let valid = signature.verify(payload_bytes, expected_signer);
            ensure!(valid, Error::<T>::InvalidSignature);
            Ok(())
        }
    }
}
