//! # Pallet ATS
//!
//! Substrate pallet for the Allfeat Timestamp Service (ATS).
//!
//! Stores tamper-proof, timestamped commitments for musical works on-chain.
//! Only the 32-byte SHA-256 commitment hash goes on-chain; all data stays off-chain
//! and is generated by the `ats-sdk` crate.
//!
//! ## Features
//!
//! - **Auto-incremented IDs** (`u64`) for each ATS entry
//! - **Versioning**: each ATS can have multiple versions, each with its own commitment
//! - **Deposits**: configurable base and version deposits using fungible holds
//! - **Hard delete on revocation**: full cleanup with deposit restitution

#![cfg_attr(not(feature = "std"), no_std)]

extern crate alloc;

mod types;
pub use types::*;

/// Weight information for pallet extrinsics.
pub mod weights;
pub use weights::WeightInfo;

#[cfg(feature = "runtime-benchmarks")]
mod benchmarking;

#[cfg(test)]
mod mock;

#[cfg(test)]
mod tests;

/// ATS identifier type (auto-incremented `u64`).
pub type AtsId = u64;

pub use pallet::*;

#[frame_support::pallet]
pub mod pallet {
    use super::*;
    use frame_support::{
        pallet_prelude::*,
        traits::fungible::{self, hold::Mutate as FunHoldMutate},
        traits::tokens::Precision,
    };
    use frame_system::pallet_prelude::*;

    /// Balance type derived from the pallet's currency configuration.
    pub type BalanceOf<T> = <<T as Config>::Currency as fungible::Inspect<
        <T as frame_system::Config>::AccountId,
    >>::Balance;

    /// Concrete ATS record type for this pallet's configuration.
    pub type AtsRecordOf<T> =
        AtsRecord<<T as frame_system::Config>::AccountId, BlockNumberFor<T>, BalanceOf<T>>;

    /// Concrete version record type for this pallet's configuration.
    pub type VersionRecordOf<T> = VersionRecord<BlockNumberFor<T>, BalanceOf<T>>;

    #[pallet::pallet]
    pub struct Pallet<T>(_);

    /// Configuration trait for the ATS pallet.
    #[pallet::config]
    pub trait Config: frame_system::Config {
        /// The overarching hold reason type.
        type RuntimeHoldReason: From<HoldReason>;

        /// The currency type supporting fungible holds.
        type Currency: fungible::Inspect<Self::AccountId>
            + fungible::Mutate<Self::AccountId>
            + fungible::hold::Inspect<Self::AccountId, Reason = Self::RuntimeHoldReason>
            + fungible::hold::Mutate<Self::AccountId, Reason = Self::RuntimeHoldReason>;

        /// Base deposit required to create a new ATS entry.
        #[pallet::constant]
        type BaseDeposit: Get<BalanceOf<Self>>;

        /// Deposit required per version of an ATS entry.
        #[pallet::constant]
        type VersionDeposit: Get<BalanceOf<Self>>;

        /// Maximum number of versions allowed per ATS entry.
        #[pallet::constant]
        type MaxVersionsPerAts: Get<u32>;

        /// Maximum number of ATS entries allowed per account.
        #[pallet::constant]
        type MaxAtsPerAccount: Get<u32>;

        /// Weight information for pallet extrinsics.
        type WeightInfo: crate::WeightInfo;
    }

    /// Reasons for holding funds.
    #[pallet::composite_enum]
    pub enum HoldReason {
        /// Deposit for creating an ATS entry.
        #[codec(index = 0)]
        AtsDeposit,
        /// Deposit for adding a version to an ATS entry.
        #[codec(index = 1)]
        VersionDeposit,
    }

    /// Auto-incrementing counter for the next ATS identifier.
    #[pallet::storage]
    pub type NextAtsId<T: Config> = StorageValue<_, u64, ValueQuery>;

    /// Registry mapping ATS IDs to their records.
    #[pallet::storage]
    pub type AtsRegistry<T: Config> =
        StorageMap<_, Blake2_128Concat, AtsId, AtsRecordOf<T>, OptionQuery>;

    /// Double map storing version records for each ATS entry.
    #[pallet::storage]
    pub type AtsVersions<T: Config> = StorageDoubleMap<
        _,
        Blake2_128Concat,
        AtsId,
        Blake2_128Concat,
        u32,
        VersionRecordOf<T>,
        OptionQuery,
    >;

    /// Index mapping account IDs to their owned ATS entries.
    #[pallet::storage]
    pub type OwnerIndex<T: Config> = StorageMap<
        _,
        Blake2_128Concat,
        T::AccountId,
        BoundedVec<AtsId, T::MaxAtsPerAccount>,
        ValueQuery,
    >;

    /// Events emitted by the ATS pallet.
    #[pallet::event]
    #[pallet::generate_deposit(pub(super) fn deposit_event)]
    pub enum Event<T: Config> {
        /// A new ATS entry was created.
        AtsCreated {
            /// The assigned ATS identifier.
            ats_id: AtsId,
            /// The account that created the entry.
            owner: T::AccountId,
            /// The SHA-256 commitment hash.
            commitment: [u8; 32],
            /// The protocol version.
            protocol_version: u8,
        },
        /// An ATS entry was updated with a new version.
        AtsUpdated {
            /// The ATS identifier.
            ats_id: AtsId,
            /// The new version number.
            version: u32,
            /// The SHA-256 commitment hash for this version.
            commitment: [u8; 32],
            /// The protocol version.
            protocol_version: u8,
        },
        /// An ATS entry was revoked and all deposits returned.
        AtsRevoked {
            /// The revoked ATS identifier.
            ats_id: AtsId,
            /// The owner who revoked the entry.
            owner: T::AccountId,
        },
    }

    /// Errors returned by the ATS pallet.
    #[pallet::error]
    pub enum Error<T> {
        /// The specified ATS entry was not found.
        AtsNotFound,
        /// The caller is not the owner of the ATS entry.
        NotOwner,
        /// Maximum number of versions reached for this ATS entry.
        MaxVersionsReached,
        /// Invalid protocol version (must be non-zero).
        InvalidProtocolVersion,
        /// Maximum number of ATS entries per account reached.
        MaxAtsPerAccountReached,
        /// Arithmetic overflow occurred.
        ArithmeticOverflow,
    }

    #[pallet::call]
    impl<T: Config> Pallet<T> {
        /// Create a new ATS entry with an initial version (version 0).
        ///
        /// Holds `BaseDeposit + VersionDeposit` from the caller's balance.
        #[pallet::call_index(0)]
        #[pallet::weight(T::WeightInfo::create())]
        pub fn create(
            origin: OriginFor<T>,
            commitment: [u8; 32],
            protocol_version: u8,
        ) -> DispatchResult {
            let who = ensure_signed(origin)?;
            ensure!(protocol_version > 0, Error::<T>::InvalidProtocolVersion);

            // Check owner capacity
            let mut ids = OwnerIndex::<T>::get(&who);
            ids.try_push(0) // dummy value to test capacity
                .map_err(|_| Error::<T>::MaxAtsPerAccountReached)?;
            ids.pop(); // remove the dummy

            // Allocate next ID
            let ats_id = NextAtsId::<T>::get();
            let next_id = ats_id
                .checked_add(1)
                .ok_or(Error::<T>::ArithmeticOverflow)?;

            // Hold deposits
            let base_deposit = T::BaseDeposit::get();
            let version_deposit = T::VersionDeposit::get();
            <T::Currency as FunHoldMutate<T::AccountId>>::hold(
                &HoldReason::AtsDeposit.into(),
                &who,
                base_deposit,
            )?;
            <T::Currency as FunHoldMutate<T::AccountId>>::hold(
                &HoldReason::VersionDeposit.into(),
                &who,
                version_deposit,
            )?;

            let now = frame_system::Pallet::<T>::block_number();

            // Write storage
            AtsRegistry::<T>::insert(
                ats_id,
                AtsRecordOf::<T> {
                    owner: who.clone(),
                    created_at: now,
                    version_count: 1,
                    base_deposit,
                },
            );

            AtsVersions::<T>::insert(
                ats_id,
                0u32,
                VersionRecordOf::<T> {
                    commitment,
                    protocol_version,
                    created_at: now,
                    deposit: version_deposit,
                },
            );

            // Update owner index (capacity already verified)
            ids.try_push(ats_id).expect("capacity checked above; qed");
            OwnerIndex::<T>::insert(&who, ids);
            NextAtsId::<T>::put(next_id);

            Self::deposit_event(Event::AtsCreated {
                ats_id,
                owner: who,
                commitment,
                protocol_version,
            });

            Ok(())
        }

        /// Add a new version to an existing ATS entry.
        ///
        /// Holds `VersionDeposit` from the caller's balance. Only the owner can update.
        #[pallet::call_index(1)]
        #[pallet::weight(T::WeightInfo::update())]
        pub fn update(
            origin: OriginFor<T>,
            ats_id: AtsId,
            commitment: [u8; 32],
            protocol_version: u8,
        ) -> DispatchResult {
            let who = ensure_signed(origin)?;
            ensure!(protocol_version > 0, Error::<T>::InvalidProtocolVersion);

            let mut record = AtsRegistry::<T>::get(ats_id).ok_or(Error::<T>::AtsNotFound)?;
            ensure!(record.owner == who, Error::<T>::NotOwner);

            let version = record.version_count;
            ensure!(
                version < T::MaxVersionsPerAts::get(),
                Error::<T>::MaxVersionsReached
            );
            let new_count = version
                .checked_add(1)
                .ok_or(Error::<T>::ArithmeticOverflow)?;

            // Hold version deposit
            let version_deposit = T::VersionDeposit::get();
            <T::Currency as FunHoldMutate<T::AccountId>>::hold(
                &HoldReason::VersionDeposit.into(),
                &who,
                version_deposit,
            )?;

            let now = frame_system::Pallet::<T>::block_number();

            AtsVersions::<T>::insert(
                ats_id,
                version,
                VersionRecordOf::<T> {
                    commitment,
                    protocol_version,
                    created_at: now,
                    deposit: version_deposit,
                },
            );

            record.version_count = new_count;
            AtsRegistry::<T>::insert(ats_id, record);

            Self::deposit_event(Event::AtsUpdated {
                ats_id,
                version,
                commitment,
                protocol_version,
            });

            Ok(())
        }

        /// Revoke an ATS entry, deleting all versions and returning all deposits.
        ///
        /// This is a hard delete: all data is removed from storage. Only the owner can revoke.
        /// Weight is linear in the number of versions.
        #[pallet::call_index(2)]
        #[pallet::weight(T::WeightInfo::revoke(T::MaxVersionsPerAts::get()))]
        pub fn revoke(origin: OriginFor<T>, ats_id: AtsId) -> DispatchResult {
            let who = ensure_signed(origin)?;

            let record = AtsRegistry::<T>::get(ats_id).ok_or(Error::<T>::AtsNotFound)?;
            ensure!(record.owner == who, Error::<T>::NotOwner);

            // Release all version deposits and clean up version storage
            for version in 0..record.version_count {
                if let Some(version_record) = AtsVersions::<T>::take(ats_id, version) {
                    <T::Currency as FunHoldMutate<T::AccountId>>::release(
                        &HoldReason::VersionDeposit.into(),
                        &who,
                        version_record.deposit,
                        Precision::Exact,
                    )?;
                }
            }

            // Release base deposit
            <T::Currency as FunHoldMutate<T::AccountId>>::release(
                &HoldReason::AtsDeposit.into(),
                &who,
                record.base_deposit,
                Precision::Exact,
            )?;

            // Remove from registry
            AtsRegistry::<T>::remove(ats_id);

            // Remove from owner index
            let mut ids = OwnerIndex::<T>::get(&who);
            ids.retain(|id| *id != ats_id);
            if ids.is_empty() {
                OwnerIndex::<T>::remove(&who);
            } else {
                OwnerIndex::<T>::insert(&who, ids);
            }

            Self::deposit_event(Event::AtsRevoked { ats_id, owner: who });

            Ok(())
        }
    }
}
