//! Data types for the ATS SDK.

use alloc::string::String;
use alloc::vec::Vec;

use crate::hash::Hash;
use crate::merkle::{MerkleProof, MerkleTree, NUM_LEAVES};

/// Current protocol version. Included in the commitment preimage.
pub const PROTOCOL_VERSION: u8 = 1;

/// Maximum number of creators per work (derived from Merkle tree capacity).
pub const MAX_CREATORS: usize = NUM_LEAVES;

// ----- Role -----

/// Role a creator can hold in a musical work.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[repr(u8)]
pub enum Role {
    /// Lyricist / text author.
    Author = 0,
    /// Music composer.
    Composer = 1,
    /// Arranger of an existing work.
    Arranger = 2,
    /// Adapter of an existing work.
    Adapter = 3,
}

// ----- Creator -----

/// A creator (contributor) of a musical work.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Creator {
    /// Full legal name.
    pub full_name: String,
    /// Contact email address.
    pub email: String,
    /// Roles held by this creator (at least one required).
    pub roles: Vec<Role>,
    /// IPI code (Interested Parties Information), 1-11 digits.
    pub ipi: Option<String>,
    /// ISNI code, exactly 16 characters `[0-9X]`.
    pub isni: Option<String>,
}

// ----- AtsInput -----

/// All user-provided data for registering a musical work.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AtsInput {
    /// Title of the musical work.
    pub title: String,
    /// List of creators (1 to [`MAX_CREATORS`]).
    pub creators: Vec<Creator>,
}

// ----- On-chain commitment -----

/// The minimal data that goes on-chain.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct OnChainCommitment {
    /// The final binding commitment hash.
    pub commitment: Hash,
    /// Protocol version used to generate this commitment.
    pub protocol_version: u8,
}

// ----- AtsProof -----

/// Full proof generated by the SDK. Contains both the on-chain commitment
/// and all off-chain data needed for the certificate and proof generation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AtsProof {
    /// Data to submit on-chain (commitment + version).
    pub on_chain: OnChainCommitment,
    /// SHA-256 of the media file bytes.
    pub media_hash: Hash,
    /// Full Merkle tree (stores leaves, internal nodes, and root).
    pub merkle_tree: MerkleTree,
}

impl AtsProof {
    /// Root of the creators Merkle tree.
    #[must_use]
    pub fn creators_merkle_root(&self) -> Hash {
        self.merkle_tree.root()
    }

    /// All leaf hashes (32 entries, padded with zero leaves).
    #[must_use]
    pub fn creator_leaves(&self) -> &[Hash] {
        self.merkle_tree.leaves()
    }

    /// Generate a Merkle inclusion proof for the creator at `index`.
    ///
    /// # Panics
    /// Panics if `index >= 32`.
    #[must_use]
    pub fn creator_proof(&self, index: usize) -> MerkleProof {
        self.merkle_tree.proof(index)
    }
}
